### ISSUE TITLE
Can't get this running in my repository

### ISSUE THREAD

**Issue by ReynoldsCahoon** [davidcraig/action-wow-lint#1]
Hey there, new to Github Actions so I might be making a beginner mistake, but I've included this in my github actions

![image](https://user-images.githubusercontent.com/2556251/163857293-cf687f1b-1590-43a2-8407-d4726a21f8eb.png)

And this is the result
![image](https://user-images.githubusercontent.com/2556251/163857163-d30d9cfa-e318-4ba3-b576-237c7bd3e055.png)

Is there something I've done wrong? I also attempted changing the version to `1.0.0` with similar results.

**Comment by davidcraig** [comment]
change

    uses: davidcraig/action-wow-lint@1.0.1

to

    uses: davidcraig/action-wow-lint@v1.0.1


Here is an example working: https://github.com/wow-addon/Broker_CurrencyFlow/blob/master/.github/workflows/lint.yml

**Comment by davidcraig** [comment]
Seems I need to update the readme to include the v :D

**Comment by ReynoldsCahoon** [comment]
Thank you for your help! That resolved the issue.

Is it possible to bulk include any `.lua` files in the repository in the check, rather than pointing specifically to each file? Is the syntax `*.lua` acceptable?

**Comment by davidcraig** [comment]
Yes it uses Linux glob under the hood and passes to luac to check - so
`*.lua` should work maybe `**/*.lua
`
to make sure it checks subdirectories too? :)

~~Extra asterisks are missing due to markdown parser and I'm on phone but hopefully you understand what I mean ~~

Edit 2: Fixed formatting
